version: '3.8'

# Network
networks:
  web_network:
    name: mainnetwork
    driver: bridge
services:
  #####################
  ### WebApp Nodejs
  #####################
  app:
    restart: unless-stopped
    build: .
##    Uncomment this if you want to expose app too.
    ports:
      - 3001:3001
    # command: node index.js
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - web_network

  #####################
  ### Nginx Web Service
  #####################
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - 8101:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web_network