# Network
networks:
  web_network:
    name: mainnetwork
    driver: bridge

services:

  # App Service 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeJS
    networks:
      - web_network